version: "3.9"

services:
  mongodb:
    image: mongo:6
    container_name: mongodb_container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: barber_club
      MONGO_INITDB_ROOT_PASSWORD: inicio@1
      MONGO_INITDB_DATABASE: barber_club
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

volumes:
  mongodb_data:
    driver: local

networks:
  app_network:
    driver: bridge
